name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    
    runs-on: macos-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
        xcode: ['/Applications/Xcode_11.3.app/Contents/Developer']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dependencies
        run: pod install
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }} 
      - name: Build and test
        run: bundle exec fastlane scan --destination "${destination}" --scheme "Norris"
        env:
          destination: ${{ matrix.destination }}
          DEVELOP_DIR: ${{ matrix.xcode }}
      - name: Archive Failed Tests artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with: 
          name: FailureDiff
          path: NorrisTests/FailureDiffs    
