on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    
    runs-on: macos-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dependencies
        run: pod install
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }} 
      - name: Build and test
        run: xcodebuild clean test -workspace Norris.xcworkspace -scheme Norris -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          destination: ${{ matrix.destination }}
          DEVELOP_DIR: ${{ matrix.xcode }}
      - name: Archive Failed Tests artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with: 
          name: FailureDiff
          path: NorrisTests/FailureDiffs    
